### PR TITLE
NEW PLUGIN OCR!

### PR DESCRIPTION
**Pull request by justinthoms**

### CODE REVIEW

**Comment by Quiec** [comment]
Wow, thank you.
Have you tried?

**Comment by justinthoms** [comment]
yest it working only {eng}

**Comment by Quiec** [comment]
@justinthoms I will download it myself and make additions.

Is it okay to give you author?

**Comment by justinthoms** [comment]
sure make additions. more lang.

**Comment by Quiec** [comment]
added with last commit(s)

**Pull request closed without merging**
